language: ruby
cache: bundler
notifications:
  email: false
services:
  - postgresql
before_script:
  - psql -c 'create database "last-time-webapp_test";' -U postgres
  - yarn install
  - RAILS_ENV=test bundle exec rails webpacker:compile
