notifications:
  email: false

env:
  - DOCKER_COMPOSE_VERSION=1.24.0
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

services:
  - docker

install:
  - docker-compose build
before_script:
  - docker-compose run rails bundle install
  - docker-compose run rails bin/yarn install
  - docker-compose run -e RAILS_ENV=test rails bin/rails webpacker:compile
  - docker-compose run -e RAILS_ENV=test rails bin/rails db:create
script:
  - docker-compose run -e RAILS_ENV=test -e CI=true -e CODECOV_TOKEN=$CODECOV_TOKEN rails bin/rails test
